/*
https://leetcode.com/problems/find-the-difference/

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
*/

var findTheDifference = function (s, t) {
    let h = {}

    for(let char of s) {
        if(h[char]) h[char] ++
        else h[char] = 1
    }

    for (let char of t) {
        if (h[char]) h[char]--
        else return char
    }

};